# config/__init__.py
# -*- coding: utf-8 -*-

from config.hardware import *

__all__ = [
    "PWM_PIN",
    "PWM_FREQ_HZ",
    "RELE_BOMBA_PIN",
    "VALV_PIN",
    "USE_VALVULA",
    "VALV_ACTIVE_HIGH",
    "BOMBA_ACTIVE_LOW",
    "FAN_PWM_PIN",
    "FAN_PWM_FREQ_HZ",
    "DS18B20_GPIO",
    "TEMP_TARGET_C",
    "TEMP_FULLSPEED_C",
    "TEMP_HYST_C",
    "FAN_PWM_MIN",
    "FAN_PWM_MAX",
    "FAN_FAILSAFE_FULLSPEED",
    "FAN_FAILSAFE_PWM",
    "P_MAX_SEGURIDAD_KPA",
    "P_MIN_KPA",
    "ADS_I2C_BUS",
    "ADS_ADDR",
    "ADS_PGA_V",
    "ADS_SPS",
    "ADS_CONV_DELAY_S",
    "VADC_MIN_OK",
    "VADC_MAX_OK",
    "ADS_CH_DUT_V",
    "ADS_CH_DUT_mA",
    "ADS_CH_REF",
    "USE_ADS_REF",
    "A0_VIN_GAIN",
    "A0_VIN_OFFSET",
    "USE_A0_CAL",
    "A1_IMA_GAIN",
    "A1_IMA_OFFSET",
    "USE_A1_CAL",
    "A0_CAL_M",
    "A0_CAL_B",
    "A1_CAL_M",
    "A1_CAL_B",
    "A2_CAL_M",
    "A2_CAL_B",
    "N_SAMPLES_AVG",
    "SAMPLE_DT_AVG_S",
    "N_SAMPLES_MEASURE",
    "SAMPLE_DT_MEASURE_S",
    "MEASURE_MEDIAN_ENABLE",
    "MEASURE_MEDIAN_N",
    "FILTER_LIVE_ENABLE",
    "A0_MEDIAN_N",
    "A0_MEAN_N",
    "A1_MEDIAN_N",
    "A1_MEAN_N",
    "A2_MEDIAN_N",
    "A2_MEAN_N",
    "DUT_CURRENT_LIVE_MIN_PERIOD_S",
    "DUT_CURRENT_DISPLAY_HYST_MA",
    "DUT_PRESSURE_DISPLAY_HYST_KPA",
    "DUT_ERROR_DISPLAY_HYST_PCT",
    "MPX_A2",
    "MPX_B2",
    "MPX_C2",
    "USE_2PT",
    "GAIN_2PT",
    "OFFSET_2PT",
    "FFT_N_SAMPLES",
    "FFT_USE_WINDOW",
    "PI_CFG",
]

